### ISSUE TITLE
TemplateSyntaxError: Encountered unknown tag 'assets'.

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre-attack/attack-website#32]
Good afternoon ATT&CK team,

I was giving a try to the build, and after running `python3 update-attack.py -c -b`, I got the following error:

```
Clean Build            : ---------------------------------------- 0.59s      
Downloading STIX Data  : ---------------------------------------- 1.18s      
Initializing Data      : ---------------------------------------- 37.38s      
Index Page             : ---------------------------------------- 0.35s      
Group Pages            : ---------------------------------------- 3.07s      
Software Pages         : ---------------------------------------- 8.63s      
Technique Pages        : ---------------------------------------- 7.11s      
Matrix Pages           : ---------------------------------------- 7.99s      
Tactic Pages           : ---------------------------------------- 0.79s      
Mitigation Pages       : ---------------------------------------- 0.45s      
Contribute Page        : ---------------------------------------- 0.10s      
Resources Page         : ---------------------------------------- 0.00s      
Redirection Pages      : ---------------------------------------- 0.50s      
Search Index           : ---------------------------------------- 148.65s      
Previous Versions      : ---------------------------------------- 9.07s      
Pelican Content        : ---------------------------------------- Running...CRITICAL: TemplateSyntaxError: Encountered unknown tag 'assets'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
Traceback (most recent call last):
  File "update-attack.py", line 282, in <module>
    update(args)
  File "update-attack.py", line 149, in update
    generate.pelican_content()
  File "/opt/ATTACK/modules/generate.py", line 107, in pelican_content
    returned_out = subprocess.check_output("pelican content -q", shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'pelican content -q' returned non-zero exit status 1
```

Any idea how I can get to the template where Jinja is looking for `endblock`? Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
Got it working. It was a permissions on plugins folder I believe. I had initially cloned the repo to /opt. Tested it on home path and it worked fine :) I usually update rights to /opt, but I was testing it with the `sudo` command to run `python3 update-attack.py` . I ended up doing this :) 

```
ubuntu@ip-192-168-1-6:~$ git clone https://github.com/mitre-attack/attack-website
Cloning into 'attack-website'...
remote: Enumerating objects: 12830, done.
remote: Counting objects: 100% (12830/12830), done.
remote: Compressing objects: 100% (3471/3471), done.
remote: Total 52773 (delta 7102), reused 11775 (delta 6074), pack-reused 39943
Receiving objects: 100% (52773/52773), 110.25 MiB | 30.69 MiB/s, done.
Resolving deltas: 100% (27474/27474), done.
ubuntu@ip-192-168-1-6:~$ cd attack-website/
ubuntu@ip-192-168-1-6:~/attack-website$ ls
CHANGELOG.md     LICENSE.txt  README.md     content  modules         plugins           update-attack.py
CONTRIBUTING.md  NOTICE.txt   attack-theme  data     pelicanconf.py  requirements.txt
ubuntu@ip-192-168-1-6:~/attack-website$ python3 update-attack.py -c -b
Clean Build            : ---------------------------------------- 0.00s      
Downloading STIX Data  : ---------------------------------------- 1.63s      
Initializing Data      : ---------------------------------------- 37.57s      
Index Page             : ---------------------------------------- 0.35s      
Group Pages            : ---------------------------------------- 3.05s      
Software Pages         : ---------------------------------------- 8.54s      
Technique Pages        : ---------------------------------------- 7.07s      
Matrix Pages           : ---------------------------------------- 7.97s      
Tactic Pages           : ---------------------------------------- 0.79s      
Mitigation Pages       : ---------------------------------------- 0.44s      
Contribute Page        : ---------------------------------------- 0.11s      
Resources Page         : ---------------------------------------- 0.00s      
Redirection Pages      : ---------------------------------------- 0.51s      
Search Index           : ---------------------------------------- 149.06s      
Previous Versions      : ---------------------------------------- 9.65s      
Pelican Content        : ---------------------------------------- 16.03s      

Running tests:
---------------------------------------  -------------------------------------------------------  ------------------------------------------------------- 
STATUS                                   TEST                                                     MESSAGE                                                 
---------------------------------------  -------------------------------------------------------  ------------------------------------------------------- 
PASSED                                   Output Folder Size                                       Size: 671.90 MB                                         
PASSED                                   Internal Links                                           5438 OK - 0 broken link(s)                              
PASSED                                   Unlinked Pages                                           0 unlinked page(s)                                      
PASSED                                   Relative Links                                           0 page(s) with relative link(s) found                   
PASSED                                   Broken Citations                                         3308 pages OK, 0 pages broken                           
---------------------------------------  -------------------------------------------------------  ------------------------------------------------------- 

5 tests passed, 0 tests failed

TOTAL Build Time       : ---------------------------------------- 243.17s      
TOTAL Test Time        : ---------------------------------------- 11.53s      
TOTAL Update Time      : ---------------------------------------- 254.70s 
```

Sorry for the inconvenience.
