### ISSUE TITLE
Docker build error on v4.0.0

### ISSUE THREAD

**Issue by jmosby1** [mitre-attack/attack-website#391]
I'm encountering the below error when trying to build the Docker container after v4.0.0 release.  The build environment is the same one I used for v3.6.7, and I confirmed I can still build the old container just fine. 
Building on Windows 10, Python version 3.10.8

```
C:\...\attack-website> docker build -t website-test:latest .
[+] Building 4.0s (9/10)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                    2.3s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 31.23kB                                                                               0.1s
 => [1/6] FROM docker.io/library/ubuntu:20.04@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec6  0.0s
 => CACHED [2/6] COPY . /home/attackuser/attack-website                                                            0.0s
 => CACHED [3/6] RUN apt-get update --fix-missing   && apt-get install -qqy --no-install-recommends   locales nan  0.0s
 => CACHED [4/6] WORKDIR /home/attackuser/attack-website                                                           0.0s
 => ERROR [5/6] RUN python3 update-attack.py --no-test-exitstatus                                                  1.5s
------
 > [5/6] RUN python3 update-attack.py --no-test-exitstatus:
#8 1.411 Traceback (most recent call last):
#8 1.411   File "update-attack.py", line 8, in <module>
#8 1.411     import modules
#8 1.411   File "/home/attackuser/attack-website/modules/__init__.py", line 38, in <module>
#8 1.411     imported_module = __import__("modules" + "." + module, fromlist=[module])
#8 1.411   File "/home/attackuser/attack-website/modules/resources/__init__.py", line 1, in <module>
#8 1.411     from . import resources
#8 1.411   File "/home/attackuser/attack-website/modules/resources/resources.py", line 8, in <module>
#8 1.411     from mitreattack.attackToExcel import attackToExcel
#8 1.411   File "/usr/local/lib/python3.8/dist-packages/mitreattack/attackToExcel/attackToExcel.py", line 7, in <module>
#8 1.411     import pandas as pd
#8 1.411   File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 48, in <module>
#8 1.411     from pandas.core.api import (
#8 1.411   File "/usr/local/lib/python3.8/dist-packages/pandas/core/api.py", line 22, in <module>
#8 1.411     from pandas.core.algorithms import (
#8 1.411   File "/usr/local/lib/python3.8/dist-packages/pandas/core/algorithms.py", line 40, in <module>
#8 1.411     from pandas.core.dtypes.cast import (
#8 1.411   File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py", line 23, in <module>
#8 1.411     from dateutil.parser import ParserError
#8 1.411 ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/usr/lib/python3/dist-packages/dateutil/parser/__init__.py)
------
executor failed running [/bin/sh -c python3 update-attack.py --no-test-exitstatus]: exit code: 1
```

**Comment by jondricek** [comment]
Looks like that particular error is coming from the fact that the [python-dateutil](https://pypi.org/project/python-dateutil/) package that is installed in the docker container is old. I just added the line `python-dateutil==2.8.2` to the `requirements.txt` file and ran the command and it is getting past that issue now. With any luck, that should be the only fix needed.

**Comment by jondricek** [comment]
Also, a probably better approach is for us to update the base build image from Ubuntu 20.04 up to 22.04, so I'll plan to do that as well here.

**Comment by jmosby1** [comment]
Thanks @jondricek, the Ubuntu base image change fixed the issue for me
